### ISSUE TITLE
webbtc.com

### ISSUE THREAD

**Issue by dranes** [mhanne/block_browser#1]
Sorry maybe this is not the right place to ask this but i think you're in charge of the site http://webbtc.com.

From yesterday the site is not working and i was using your api because is the most completed and easy i found, and i'm curious is the site is gonna be back any soon ? 

Thanks and sorry again

**Comment by adr7929** [comment]
Hi, I am recently using the resource on the website "http://webbtc.com" as well, really appreciated for the great work. Just earlier today I found the website was down. Is there any estimate timing when will it be back on again? Thanks again for the effort.

**Comment by mhanne** [comment]
Whoops. I'm sorry, the instance ran out of space during a db dump, I had restarted the nodes but didn't notice the webservers had crashed too m(

Thanks for letting me know!

**Comment by adr7929** [comment]
No problem, Thanks a lot for your time :)

**Comment by jvrocamora** [comment]
not running the site. its down

**Comment by patha046** [comment]
@mhanne  http://dumps.webbtc.com/ is down. When will it be back?

**Comment by javierlopeza** [comment]
I'm not able to make requests to the API.

For example,
`https://webbtc.com/api/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16.json`

> This webbtc.com page can’t be found
