### ISSUE TITLE
error not thrown for non-minimally encoded stack integers

### ISSUE THREAD

**Issue by mulllhausen** [mhanne/block_browser#16]
hi, just running the following script in webbtc.com/scripts and its not throwing an error when it should be:

    input: ff0080
    output: OP_NEGATE OP_NEGATE

the middle `0x00` is redundant, and since `OP_NEGATE` calls `CScriptNum` with `fRequireMinimal` the core client would throw an error here. it would be good to at least put a warning so that others will be aware that this script will not evaluate correctly in production.

also, thanks for the webbtc script tool - i have found it very useful!

cheers,
peter

**Comment by mhanne** [comment]
Hi Peter,

good point, all the verification flags are now enabled by default and you can disable them separately. This works with an input script of `01`, for example, to trigger `verify_minimaldata`.

But unfortunately your specific example still doesn't work, see https://github.com/lian/bitcoin-ruby/issues/168.
