### ISSUE TITLE
A few transactions missing

### ISSUE THREAD

**Issue by cassiniNMC** [mhanne/block_browser#24]
A few transactions are being ignored by the block_browser instance at webbtc.com, e.g.

http://namecoin.webbtc.com/tx/9b1eaeca2f5b2bd3b1d0b903b0c92cb3d386812303e46eb9130d4293b19a337b
says "... something went wrong".
The tx does exist, though, see http://namecoin.webbtc.com/address/N6cs2y1k1P3FpVnWE4csBsWDBiuF326gLy
 and http://namecoin.webbtc.com/block/e9fcd86cc18c277517d81af100ff5c6dcfcac9c483e642e49819c362af603cba
Also, webbtc cannot find the name related to this tx: http://namecoin.webbtc.com/name/d/epinymtest

http://namecoin.webbtc.com/tx/cf8bcb4e3be8f952fe9800e08866d0f19952068adfa9b27d9342fd95932219e8
says "... something went wrong".
The tx does exist, though, see http://namecoin.webbtc.com/address/NJdUzDw2qvgLMC3H4sJNGcjc5cZNppFxY7
 and http://namecoin.webbtc.com/block/7412bc038030f89c2c77313f4e4038a137346b62d352d77bba1a560ad11d730b
Also, http://namecoin.webbtc.com/name/d/meowmix shows only 1 operation. Should be more than one.

**Comment by mhanne** [comment]
Thanks for reporting this!

It was a stupid bug with checking that the `name_new` has at least 12 confirmations before the `name_firstupdate` becomes valid. This should fix it and let the names be registered properly:
https://github.com/mhanne/namecoin-ruby/commit/a9063cb9e01e51bc87cdf8bc2311927ef492bcd6
(DB is rebuilding now, so it'll be a while before the missing names show up...)

**Comment by mhanne** [comment]
All the names / transactions you listed are now showing up properly.

Now only these 3 transactions are still having problems:
58d84e44184469125d384fb9eb2497dc6fee3643b906036c74fb00b1e82651b9
8aa2b0fc7d1033de28e0192526765a72e9df0c635f7305bdc57cb451ed01a4ca
a2231c70cbec314cffe667f2b1eb0ce6ec566d951fdf0262635997987d470a84

These should be fixed after https://github.com/mhanne/namecoin-ruby/issues/3.
