### ISSUE TITLE
Time should be displayed as UTC

### ISSUE THREAD

**Issue by cassiniNMC** [mhanne/block_browser#25]
(Possibly related to [commit dd0dced](https://github.com/mhanne/block_browser/commit/dd0dced3f0a4986985803a0c82689d8dcf4789a6))
The "Time" column of the webbtc instance shows the timestamps as CET/CEST. This leads to the confusing situation that it looks as if Namecoin block 254714 was found 46 mins. after block 254715 (they were mined around the switch from CEST to CET).
UTC avoids these problems. Furthermore, UTC makes it easier to match the blockchain data with other events, e.g. a large mining pool going offline/online.

**Comment by mhanne** [comment]
You're right, everything else than UTC just leads to confusion. Stupid time switches :P

The commit you referenced fixed it already, but only for the special case of the block timestamp inside the tx json output. Now all times should be in UTC.
