### ISSUE TITLE
webbtc.com_database dump

### ISSUE THREAD

**Issue by adr7929** [mhanne/block_browser#30]
Hi, I was trying to update the Bitcoin blockchain data in my PC with the latest database dump from the website. But the datebase dump hasn't seemed to work for more than a week now. Do you have any idea when it will back on again? Thanks a lot in advance!!

**Comment by mhanne** [comment]
Sorry about that, I switched the main site to SSL but the dumps server doesn't have a certificate (yet)...
Switched the link back to http for now, adding SSL support soon.
