### ISSUE TITLE
test.namecoin.webbtc.com displays incorrect addresses

### ISSUE THREAD

**Issue by cassiniNMC** [mhanne/block_browser#31]
jonasbits reported this error at a freenet #namecoin-meeting. The base58 prefix for NMC testnet addresses should be the same as in BTC testnet addresses.  
test.namecoin.webbtc.com uses a different prefix. This results in incorrect NMC testnet addresses. Example:  
http://testnet.explorer.namecoin.info/tx/b56857fded39d94d7147e9c8643101882f77af1acbf1f3fe077d2f305762bfc2 shows the target address correctly.
https://test.namecoin.webbtc.com/tx/b56857fded39d94d7147e9c8643101882f77af1acbf1f3fe077d2f305762bfc2 shows an incorrect address.

**Comment by mhanne** [comment]
Fixed, thanks for reporting!
