### ISSUE TITLE
webbtc.com testnet is stuck on block 584577

### ISSUE THREAD

**Issue by mrkent** [mhanne/block_browser#34]
Likely the node isn't connected to reliable nodes. I suggest testnet-seed.bitcoin.petertodd.org

**Comment by mhanne** [comment]
Thanks, finally fixed it now. It got stuck processing really long sidechains (some over 10k blocks).
https://github.com/mhanne/bitcoin-ruby-node/commit/74bcee331fb8c153d2a8fbf11a7ca3f3e61859ed
