### ISSUE TITLE
namecoin.webbtc.com API with http 502 Bad Gateway error

### ISSUE THREAD

**Issue by cassiniNMC** [mhanne/block_browser#45]
https://webbtc.com/stats.json works but https://namecoin.webbtc.com/stats.json doesn't, for example.
We'd like to do some tests with Jeremy Rand's SPV client which makes use of the namecoin.webbtc.com API, see https://forum.namecoin.org/viewtopic.php?p=16888

**Comment by mhanne** [comment]
Hi, sorry for being incapacitated so long...
This was really just a configuration issue and is now fixed.
I use a different rule for the API (to not force-redirect to https like the normal pages) - that was still pointing to the old upstream server...
